### PR TITLE
ci(docs): Unblock publish-docs workflow on master

### LINKED ISSUE #196: ci(docs): publish-docs.yml failing on master — NU1010 Central Package Management mismatches
## Problem

The `publish-docs.yml` workflow has been **failing on every push to `master` since at least the PR #191 merge**. The last successful run was "Updated .NET to v9" months ago. The live site at https://github.ploch.dev/ploch-common/ is therefore stale and has not been receiving updates — including the #191 modernisation and the #190 `docs/` folder wiring that is currently on PR #195.

Recent failed runs (all on master):
- After PR #193 merge (Qodana fix) — run 24612605659
- After PR #191 merge (DocFX P0 quick-wins) — earlier

## Root cause

`NU1010` errors from Central Package Management across most source projects during DocFX's MSBuild-driven metadata extraction. Sample:

```
src/Common.Maui/Common.Maui/Ploch.Common.Maui.csproj : error NU1010:
The following PackageReference items do not define a corresponding PackageVersion
item: AsyncAwaitBestPractices, CommunityToolkit.Mvvm, Microsoft.Extensions.Configuration.Json, ...
Projects using Central Package Management must declare PackageReference
and PackageVersion items with matching names.
```

Affects at least: `Ploch.Common.csproj`, `Ploch.Common.Maui.csproj`, `Ploch.Common.Maui.Tests.TestAssembly1/2.csproj`, `Ploch.Common.Extensions.Configuration.csproj`, `Ploch.TestingSupport.XUnit3.Dependencies.csproj`, `Ploch.Common.DependencyInjection(.Hosting).csproj`, `Ploch.TestingSupport.csproj`.

The mismatch is that these `.csproj` files declare `<PackageReference Include="X">` without any matching `<PackageVersion Include="X" Version="..."/>` in `Directory.Packages.props` (or vice versa). Something drifted between per-project references and the central version catalogue — possibly the `mrploch-development/dependencies/*.Packages.props` imports changed upstream without all consumers being updated.

## Why it matters

- Docs site is **stale** — the live URL does not reflect merged PRs.
- `--warningsAsErrors` (added in #190) has no effect while the step fails before reaching the DocFX build.
- Any future docs PR merges land in a workflow that is already red, masking new regressions.

## Fix direction

1. `dotnet restore Ploch.Common.slnx` locally and identify every project emitting NU1010.
2. For each project, diff its `<PackageReference>` items against `Directory.Packages.props` + the imported `mrploch-development/dependencies/*.Packages.props`.
3. Either add the missing `<PackageVersion>` entries centrally, or drop the `<PackageReference>` items that are no longer needed.
4. Verify `dotnet docfx DocumentationSite/docfx.json` completes without NU1010.

## Out of scope (for this issue)

- The Common.Maui.Tests.TestAssembly1/2 and Common.WebApi **compilation errors** (CS0234/CS0246/missing OpenApiInfo) are a separate, deeper issue — even after CPM is fixed, those projects will still fail to compile. Tracked separately.

## Related

- PR #195 (where this was surfaced)
- #190 (consumer: docs wiring relies on publish-docs actually running)
- #123 (docs overhaul umbrella)

### PR DESCRIPTION
**Pull request by kploch**
## Summary

The `publish-docs` workflow has been failing on every push to `master` since PR #191 merged — the live site at https://github.ploch.dev/ploch-common/ is stale. This PR unblocks the workflow end-to-end.

### `.github/workflows/publish-docs.yml`
- **Added `Clone mrploch-development` step.** Mirrors the step already present in `build-dotnet.yml`, `qodana_code_quality.yml`, and `release.yml`. `Directory.Packages.props` imports four shared catalogues from the sibling repo — without cloning, the imports silently no-op and `GlobalPackageReference` analyser entries (`ErrorProne.NET.CoreAnalyzers`, `Philips.CodeAnalysis.DuplicateCodeAnalyzer`, `PrimaryConstructorAnalyzer`, `ReflectionAnalyzers`, `Microsoft.Extensions.FileSystemGlobbing`) plus common app packages (`AsyncAwaitBestPractices`, `CommunityToolkit.Mvvm`) come out with no matching `PackageVersion` → NU1010.
- **Dropped `--warningsAsErrors` from the docfx invocation.** Left a comment explaining why: with the above fixed, docfx still surfaces 14 pre-existing warnings. Those deserve a dedicated cleanup pass rather than keeping the site indefinitely stale.

### `DocumentationSite/docfx.json`
- **Added excludes** for `**/*.Tests.TestAssembly*/**` and `**/Common.WebApi/**`. Neither `Common.Maui.Tests.TestAssembly1/2` nor any `Common.WebApi/*` project is in `Ploch.Common.slnx`, but docfx's `**/*.csproj` glob picks them up directly from the filesystem. They carry compile errors (`Ploch.Lists` cross-repo references, `Microsoft.OpenApi.Models` namespace moved in v2) that block metadata extraction but aren't relevant to the published API surface.

## Design Decisions

- **Root-cause fix for NU1010, not symptom-patch.** Issue #196 suggested auditing every `<PackageReference>` against the central catalogue and adding missing `<PackageVersion>` entries. The real cause is the missing clone step — the central catalogue was already complete. Fixed that instead of duplicating version entries locally.
- **Exclude broken projects rather than fix them here.** `Common.WebApi` and the Maui TestAssembly scaffolds carry substantive compile errors tracked by #197 and #155. Excluding them from docfx is a one-line change; fixing them is a separate, larger scope. **#197 stays open** — these projects still have real compile errors that someone will want to tackle, this PR only scopes them out of docs generation.
- **Temporarily trade off `--warningsAsErrors` for a working site.** The flag was added in #190 to catch doc regressions. After 2+ months of stale docs, a working-but-warn pipeline is a better state than blocked-on-warnings. Will re-enable once warnings are cleared.

## Testing

Ran the full flow locally against the sibling `mrploch-development` clone:

- `dotnet tool restore` → ok
- `dotnet docfx DocumentationSite/docfx.json` → exit 0, `Build succeeded with warning. 14 warning(s) 0 error(s)`
- `DocumentationSite/_site/` generated with `api/`, `articles/`, `docs/`, `index.html`, etc.

## Follow-ups

Tracked separately (not closed by this PR):
- **#197** — real compile errors in `Common.WebApi` and `Common.Maui.Tests.TestAssembly1/2` still need fixing; this PR only excludes them from docs.
- A new issue will be opened for the 14 remaining docfx warnings so `--warningsAsErrors` can be restored. Breakdown:
  - 4× `InvalidCref` on removed types (`nullValueMatchResult`, `DateOnly`, `TimeOnly`, `ConfigurableServicesBundle.Configuration`)
  - 3× `CS0108` Equals-hiding in auto-generated `Common.Maui.Fonts/IconFonts/FontAwesome*.cs`
  - 1× `Duplicate parameter` in `DelegatingServicesBundle` XML comment
  - 1× `InvalidXmlComment` on `AutoMockDataAttribute`
  - 2× `FailedToLoadAnalyzer` for `Microsoft.CodeAnalysis.Razor.Compiler` (docfx tool-version mismatch)
  - 1× MSBuild warning on `Ploch.TestingSupport.XUnit2.Dependencies.csproj` (xunit.runner.visualstudio 3.1.5 on NETFramework vs net6.0)
  - 2× additional InvalidCref duplicates

## Related

- Closes #196
- Refs #197 (sidestepped via exclude, not fixed)

___

## **CodeAnt-AI Description**
Unblock the docs site publish so new changes can reach GitHub Pages

### What Changed
- The docs publish workflow now clones the shared build-config repository before running, so the site can resolve shared package versions and complete successfully
- Documentation generation now ignores unrelated sample/test projects and web API projects that were breaking metadata extraction even though they are not part of the shipped solution
- The docs build no longer stops on existing warnings, allowing the site to publish while those older issues are cleaned up separately

### Impact
`✅ Fresh docs published on master`
`✅ Fewer docs publish failures`
`✅ Faster recovery from stale documentation`

[🔄 Retrigger CodeAnt AI Review](https://api.codeant.ai/pr/retrigger_review?token=INp60F7gC1P2SRBKNem_Sgm0aKvvoBt6zMyVxSZW2yc&org=mrploch)<details>
<summary><strong>💡 Usage Guide</strong></summary>

### Checking Your Pull Request
Every time you make a pull request, our system automatically looks through it. We check for security issues, mistakes in how you're setting up your infrastructure, and common code problems. We do this to make sure your changes are solid and won't cause any trouble later.

### Talking to CodeAnt AI
Got a question or need a hand with something in your pull request? You can easily get in touch with CodeAnt AI right here. Just type the following in a comment on your pull request, and replace "Your question here" with whatever you want to ask:
<pre>
<code>@codeant-ai ask: Your question here</code>
</pre>
This lets you have a chat with CodeAnt AI about your pull request, making it easier to understand and improve your code.

#### Example
<pre>
<code>@codeant-ai ask: Can you suggest a safer alternative to storing this secret?</code>
</pre>

### Preserve Org Learnings with CodeAnt
You can record team preferences so CodeAnt AI applies them in future reviews. Reply directly to the specific CodeAnt AI suggestion (in the same thread) and replace "Your feedback here" with your input:
<pre>
<code>@codeant-ai: Your feedback here</code>
</pre>
This helps CodeAnt AI learn and adapt to your team's coding style and standards.

#### Example
<pre>
<code>@codeant-ai: Do not flag unused imports.</code>
</pre>

### Retrigger review
Ask CodeAnt AI to review the PR again, by typing:
<pre>
<code>@codeant-ai: review</code>
</pre>

### Check Your Repository Health
To analyze the health of your code repository, visit our dashboard at [https://app.codeant.ai](https://app.codeant.ai). This tool helps you identify potential issues and areas for improvement in your codebase, ensuring your repository maintains high standards of code health.

</details>

### CODE REVIEW

File: DocumentationSite/docfx.json [hunk 1]
```diff
@@ -9,6 +9,8 @@
           ],
           "exclude": [
             "**/*Tests/**",
+            "**/*.Tests.TestAssembly*/**",
```
[the remark this answers is not in the document]
Comment (kploch) [reply DocumentationSite/docfx.json:12]: It's good that this is specific. I don't want to ignore everything that has `Tests` inside the name.
